### ISSUE TITLE
Suggestion to create a pypi package for this

### ISSUE THREAD

**Issue by LeetaoGoooo** [s0md3v/hue#10]

**Comment by s0md3v** [comment]
I have already considered this but the name "hue" is not available. Can you guys suggest some other name? Like Hued, Huer, HueX?

**Comment by DanielXu123** [comment]
BeautyHue

**Comment by s0md3v** [comment]
isn't that a bit too long maybe?

**Comment by LeetaoGoooo** [comment]
what about  HueM ?

**Comment by codenoid** [comment]
no, i will choose Huei'mi

**Comment by pkeeper** [comment]
Huyak!
Meas awesome delivery in russian.

**Comment by s0md3v** [comment]
I can't change the name of this repo and would prefer the pypi package name to be as similar as possible.
Something like Huer and HueX.

**Comment by pkeeper** [comment]
hue_format?
there is not a big difference between names for the end user if it's already deviated from repo name.. if there is 'hu-something' present then it'll be recognizable

also it's better to make `__all__` explicit, because some IDE's can't resolve imports properly as it is now

**Comment by s0md3v** [comment]
How about hue_py?

**Comment by shayshimon** [comment]
baby_huey?

**Comment by mingrammer** [comment]
huepy? 

`import huepy as hue`

**Comment by s0md3v** [comment]
pypi package has been uploaded with the name **huepy**.
Thanks.
