### ISSUE TITLE
Change the project license to something suitable for software

### ISSUE THREAD

**Issue by Calinou** [s0md3v/hue#15]
This project is currently under CC BY 4.0 according to the [README](https://github.com/UltimateHackers/hue#license--contribution), which is not a license considered suitable for software works (it's intended to be applied to non-software works such as documentation).

I would advise switching to the MIT license or similar, see [Choose a License](https://choosealicense.com/) for more information.

**Comment by s0md3v** [comment]
Thanks.
I am an amateur and I didn't know about it.
