### ISSUE TITLE
Ability to add new labels, colors, styles

### ISSUE THREAD

**Issue by peterxu30** [s0md3v/hue#17]
Came across this today, looks great!

I think it could be helpful if there was a way for users to add their own labels, colors, and styles in addition to the preset values.

**Comment by s0md3v** [comment]
You can add them if you have common sense and know escape sequences for colors & styles.
There can't be a way by which you can tell it to add magenta color and it will add it automatically.
Let me know if I got you wrong.

**Comment by peterxu30** [comment]
I meant if they knew the codes. Maybe less so for styles but there are certainly other colors and custom labels that can be added depending on the purpose of the application. It could be helpful to be able to do that programmatically as compared to changing the source code.

**Comment by s0md3v** [comment]
Minimalism is what makes hue better than other libraries.\
If you want a custom label for your program you can write a function which will work exactly like hue:
```python
def star(string):
    return cyan'[*]' + string
print star('Lets use the new label')
```

**Comment by peterxu30** [comment]
Fair enough, I'll close the issue.
