### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by hvgab** [s0md3v/hue#19]
Windows users can use [colorama](https://github.com/tartley/colorama) to convert from ansi.
```
import huepy
import colorama
colorama.init()
```
![image](https://i.imgur.com/V3uIQce.png)

Not sure how to get the colors bright though. Not sure if that has to be done in colorama or hue.

**Comment by s0md3v** [comment]
I don't think its a good idea to use a coloring library to create another coloring library. I mean whats the point?

**Comment by Kausta** [comment]
Windows support is currently discussed in #18, and I think what @UltimateHackers said makes sense. Hue itself is a coloring library, and it wouldn't make sense for it to be just a wrapper around another coloring library.
