### ISSUE TITLE
Write the difference with competitors in the README

### ISSUE THREAD

**Issue by ksamuel** [s0md3v/hue#20]
E.G: colorama.

It will help choosing between libs.

**Comment by s0md3v** [comment]
Done!

**Comment by ulgens** [comment]
@UltimateHackers I think the biggest competitor is crayons [[0](https://github.com/kennethreitz/crayons)] from kennethreitz, which is not in README.md yet. I couldn't consider this issue as done :)

0: https://github.com/kennethreitz/crayons

**Comment by s0md3v** [comment]
Alright, I will check it out.
