### ISSUE TITLE
The length of the string as provided by len() is incorrect.

### ISSUE THREAD

**Issue by ghost** [s0md3v/hue#25]
`len("Hello World!")` returns 12. This is expected.
`len(huepy.red("Hello World!"))` returns 21. This is not expected.

(Is there something I'm missing out on here?)

**Comment by s0md3v** [comment]
Hue doesn't color the strings with magic, it uses ANSI escape sequences to do that.
The characters of ANSI escape sequences are the reason behind the increased length.
Hue is meant to print strings, if you want measure the length of string for some programmatical operation, do it before supplying it hue.
Another solution would be to subtract the length of ANSI sequence from the returned length.
