### ISSUE TITLE
embedded colored strings unset outer colored string

### ISSUE THREAD

**Issue by ulgens** [s0md3v/hue#26]
The first thing i tried was putting a colored string inside another colored string to see if they play nice with each other, and they didn't :cry: 

![image](https://user-images.githubusercontent.com/166637/38844596-d8f2e42c-41fc-11e8-8179-63caab49112c.png)

* Python 3.6.5
* huepy 0.9.8.1
* ipython 6.3.1 on yakuake 3.0.5 (Antergos)

This exact problem is also an issue with kennethreitz/crayons. This the issue [[0](https://github.com/kennethreitz/crayons/issues/9)] (i copied issue title) and this is the solution [[1](https://github.com/kennethreitz/crayons/pull/13)] *

0: https://github.com/kennethreitz/crayons/issues/9
1: https://github.com/kennethreitz/crayons/pull/13

* PR has no answer from maintainer of the package. Apparently he doesn't like his child anymore. Shame on him.

**Comment by s0md3v** [comment]
I made this to explain why it happens

![infographic](https://i.imgur.com/BxDcMTj.png)

Let me know if you still don't understand.

**Comment by ulgens** [comment]
I already understand why it does happen, but i believe it shouldn't. If the green text is in red one, terminal style shouldn't get reseted to default, it should go back to red.

**Comment by s0md3v** [comment]
I don't think that would be possible.

**Comment by s0md3v** [comment]
Ah well, one thing we can do is to check if the input string contains an ANSI sequence and then use if else to switch style resetting.

**Comment by KOLANICH** [comment]
Just use [RichConsole.py](https://gitlab.com/KOLANICH/RichConsole.py)
